version: '3'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 1337:8000
    environment:
      - DOCKER=1
    depends_on:
      - redis
  redis:
    image: redis:alpine
  celery:
    build: ./
    command: celery -A yt_search worker -l info
    environment:
      - DOCKER=1
    depends_on:
      - redis
  celery-beat:
    build: ./
    command: celery -A yt_search beat -l info
    environment:
      - DOCKER=1
    depends_on:
      - redis