# Generated by Django 4.0.6 on 2022-07-09 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('extras_json', models.JSONField(blank=True, default=None, null=True, verbose_name='Extras JSON')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'API Provider',
                'verbose_name_plural': 'API Providers',
            },
        ),
        migrations.CreateModel(
            name='YTSearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('extras_json', models.JSONField(blank=True, default=None, null=True, verbose_name='Extras JSON')),
                ('query', models.CharField(max_length=255, unique=True, verbose_name='Query')),
            ],
            options={
                'verbose_name': 'Search Query',
                'verbose_name_plural': 'Search Queries',
            },
        ),
        migrations.CreateModel(
            name='YTSearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('extras_json', models.JSONField(blank=True, default=None, null=True, verbose_name='Extras JSON')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('published_at', models.DateTimeField(verbose_name='Published At')),
                ('thumbnail_url', models.URLField(verbose_name='Thumbnail URL')),
                ('video_id', models.CharField(max_length=255, verbose_name='Video ID')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ytsearchquery', verbose_name='Query')),
            ],
            options={
                'verbose_name': 'Search Result',
                'verbose_name_plural': 'Search Results',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('extras_json', models.JSONField(blank=True, default=None, null=True, verbose_name='Extras JSON')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='Key')),
                ('is_exhausted', models.BooleanField(default=False, verbose_name='Is Exhausted')),
                ('next_use', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Next Use Date')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.apiprovider', verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
            },
        ),
        migrations.AddIndex(
            model_name='ytsearchresult',
            index=models.Index(fields=['title', 'description'], name='api_ytsearc_title_6caea0_idx'),
        ),
        migrations.AddIndex(
            model_name='ytsearchresult',
            index=models.Index(fields=['published_at'], name='api_ytsearc_publish_ec556c_idx'),
        ),
    ]
