# Generated by Django 4.0.6 on 2022-07-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytsearchquery',
            name='latest_published_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Latest Published Date'),
        ),
    ]
