# Generated by Django 4.0.6 on 2022-07-10 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ytsearchquery_latest_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='next_use',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 11, 1, 21, 41, 867949), null=True, verbose_name='Next Use Date'),
        ),
    ]
