# Generated by Django 4.0.6 on 2022-07-10 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_apikey_next_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytsearchquery',
            name='next_page_token',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Next Page Token'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='next_use',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 11, 2, 26, 8, 263645), null=True, verbose_name='Next Use Date'),
        ),
    ]
