# Generated by Django 4.0.6 on 2022-07-10 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ytsearchquery_next_page_token_alter_apikey_next_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytsearchquery',
            name='status',
            field=models.CharField(choices=[('running', 'running'), ('complete', 'Complete')], default='complete', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='next_use',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 10, 22, 53, 53, 466670), null=True, verbose_name='Next Use Date'),
        ),
    ]
