# Generated by Django 4.0.6 on 2022-07-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_apikey_next_use_alter_ytsearchquery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='next_use',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Next Use Date'),
        ),
        migrations.AlterField(
            model_name='ytsearchquery',
            name='status',
            field=models.CharField(default='complete', max_length=255, verbose_name='Status'),
        ),
    ]
