# Generated by Django 4.0.6 on 2022-07-10 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_apikey_next_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='next_use',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Next Use Date'),
        ),
    ]
